// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	auth "github.com/onlyLTY/dockerCopilot/internal/handler/auth"
	autoupdate "github.com/onlyLTY/dockerCopilot/internal/handler/autoupdate"
	compose "github.com/onlyLTY/dockerCopilot/internal/handler/compose"
	container "github.com/onlyLTY/dockerCopilot/internal/handler/container"
	icons "github.com/onlyLTY/dockerCopilot/internal/handler/icons"
	image "github.com/onlyLTY/dockerCopilot/internal/handler/image"
	notify "github.com/onlyLTY/dockerCopilot/internal/handler/notify"
	progress "github.com/onlyLTY/dockerCopilot/internal/handler/progress"
	restartschedule "github.com/onlyLTY/dockerCopilot/internal/handler/restartschedule"
	version "github.com/onlyLTY/dockerCopilot/internal/handler/version"
	"github.com/onlyLTY/dockerCopilot/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method: http.MethodGet,
				Path:   "/",
				Handler: webindexHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auth/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	// 全局限流 + JWT 认证中间件链
	globalAuth := func(next http.HandlerFunc) http.HandlerFunc {
		return svc.RateLimitMiddleware(serverCtx.RateLimiter)(CookieJwtMiddleware(serverCtx)(next))
	}

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/container/:id",
				Handler: container.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/rename",
				Handler: container.RenameHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/restart",
				Handler: container.RestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/start",
				Handler: container.StartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/stop",
				Handler: container.StopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/:id/update",
				Handler: container.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup",
				Handler: container.BackupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/backup2compose",
				Handler: container.Backup2composeHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/container/backups",
				Handler: container.DelRestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/container/backups/restore",
				Handler: container.RestoreHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/listBackups",
				Handler: container.ListBackupsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id/logs",
				Handler: container.GetContainerLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/container/:id",
				Handler: container.ContainerInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/containers",
				Handler: container.ContainersListHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: icons.UploadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: icons.ObtainHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api/icons"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/image/:id",
				Handler: image.RemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/images",
				Handler: image.ImagesListHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/progress/:taskid",
				Handler: progress.GetProgressHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/program",
				Handler: version.UpdateProgramHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: version.VersionHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/compose",
				Handler: compose.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/compose/:name",
				Handler: compose.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose",
				Handler: compose.CreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/compose/:name",
				Handler: compose.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/compose/:name",
				Handler: compose.DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/compose/:name/up",
				Handler: compose.UpHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/auto-update",
				Handler: autoupdate.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/auto-update/:id",
				Handler: autoupdate.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/auto-update/run",
				Handler: autoupdate.RunHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/notify/config",
				Handler: notify.GetConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/notify/config",
				Handler: notify.UpdateConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/notify/test",
				Handler: notify.TestHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		rest.WithMiddleware(globalAuth, []rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/restart-schedule",
				Handler: restartschedule.ListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/restart-schedule/:id",
				Handler: restartschedule.UpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/restart-schedule/run",
				Handler: restartschedule.RunHandler(serverCtx),
			},
		}...),
		rest.WithPrefix("/api"),
	)
}
